export const PERGUNTASDATA = [
    {
        key: 'escolaridade',
        isMultipleChoice: false,
        titulo: "Qual o seu grau de formação?",
        respostas: [
            'Ensino Médio',
            'Graduação',
            'Mestrado',
            'Doutorado'
        ]
    },
    {
        key: 'linguagens',
        isMultipleChoice: true,
        titulo: "Quais linguagens de programação você conhece?",
        respostas: [
            'Bash',
            'C',
            'C++',
            'C#',
            'CSS',
            'Dart',
            'Go',
            'HTML',
            'Java',
            'JavaScript',
            'Julia',
            'Lua',
            'Kotlin',
            'MatLab',
            'Perl',
            'PHP',
            'PowerShell',
            'Python',
            'R',
            'Ruby',
            'Rust',
            'SAS',
            'Scala',
            'SQL',
            'Swift',
            'TypeScript',
          ]
    },
    {
        key: 'sistemas',
        isMultipleChoice: true,
        titulo: "Quais sistemas operacionais você conhece?",
        respostas: ['Android', 'Linux', 'macOS', 'UNIX', 'Windows']
    },
    {
        key: 'tempoExperiencia',
        isMultipleChoice: false,
        titulo: "Quanto tempo de experiência com programação você possui?",
        respostas: [
            'Menos de um ano',
            '1 ano',
            '2 anos',
            '3 anos',
            '4 anos',
            '5 ou mais anos',
          ]
    },
    {
        key: 'frameworks',
        isMultipleChoice: true,
        titulo: "Quais frameworks, bibliotecas e tecnologias você conhece?",
        respostas: [
            'Airflow',
            'Angular.js',
            'Appium',
            'Archimate',
            'ASP.NET',
            'BigCommerce',
            'BPMN (Business Process Model and Notation)',
            'CIS Controls',
            'Cisco Packet Tracer',
            'Cucumber',
            'Django',
            'Ember.js',
            'ERD (Entity-Relationship Diagram)',
            'Express.js',
            'Figma',
            'Flink',
            'Flutter',
            'GNS3',
            'Godot',
            'Google Ads',
            'Google Analytics',
            'Hadoop',
            'HubSpot',
            'Ionic',
            'jQuery Mobile',
            'JUnit',
            'Kafka',
            'Keras',
            'Magento',
            'Metasploit',
            'MITRE ATT&CK',
            'Moz',
            'MXNet',
            'Nessus',
            'NIST Cybersecurity',
            'Nmap',
            'Node.js',
            'NumPy',
            'Open vSwitch',
            'Pandas',
            'Phaser',
            'PyTorch',
            'React Native',
            'React.js',
            'Ruby on Rails',
            'Scaled Agile',
            'Scikit-Learn',
            'Scrum',
            'Selenium',
            'Shopify',
            'Snort',
            'Spark',
            'Spring',
            'Svelte',
            'SwiftUI',
            'Tableau',
            'TensorFlow',
            'TestNG',
            'Tidyverse',
            'TOGAF (The Open Group Architecture Framework)',
            'UML (Unified Modeling Language)',
            'Unit',
            'Unreal Engine',
            'Vue.js',
            'Wireshark',
            'WooCommerce',
            'Xamarin'
          ]
    },
    {
        key: 'tecnologiasEmergentes',
        isMultipleChoice: true,
        titulo: "Quais tecnologias emergentes você conhece?",
        respostas: [
            'Aprendizado de Máquina',
            'Big Data',
            'Blockchain',
            'Computação em Nuvem',
            'Edge Computing',
            'Inteligência Artificial',
            'Internet das Coisas',
            'Internet das Coisas Industrial',
            'No-code/Low-code',
            'Realidade Estendida',
          ]
    },
    {
        key: 'experienciaBancoDados',
        isMultipleChoice: false,
        titulo: "Você possui experiência com gerenciamento de banco de dados?",
        respostas: ['Sim', 'Não']
    },
    {
        key: 'experienciaMetodologia',
        isMultipleChoice: false,
        titulo: "Você já participou de projetos de desenvolvimento ágil ou metodologias similares?",
        respostas: ['Sim', 'Não']
    },
    {
        key: 'experienciaRedes',
        isMultipleChoice: false,
        titulo: "Você possui conhecimento sobre redes de computadores e protocolos de comunicação?",
        respostas: ['Sim', 'Não']
    },
    {
        key: 'experienciaCommerce',
        isMultipleChoice: false,
        titulo: "Você possui experiência ou interesse em projetos de e-commerce ou sistemas de pagamento online?",
        respostas: ['Sim', 'Não']
    },
    {
        key: 'experienciaAplicativo',
        isMultipleChoice: false,
        titulo: "Você possui experiência ou interesse em desenvolvimento de aplicativos para dispositivos móveis?",
        respostas: ['Sim', 'Não']
    },
    {
        key: 'experienciaLegados',
        isMultipleChoice: false,
        titulo: "Você já atuou em projetos de migração de sistemas legados para tecnologias modernas?",
        respostas: ['Sim', 'Não']
    }    
]
